spring:
  application:
    group: agibank
    name: analytics

server:
  port: 8080

app:
  homepath: ${HOMEPATH:${HOME}}
  delimiters:
    column: ${COLUMN_DELIMITER:รง}
    item: ${ITEM_DELIMITER:,}
    property-item: ${PROPERTY_ITEM_DELIMITER:-}